name: e2e-ios

on: pull_request

env:
  NO_FLIPPER: 1
  E2E_TESTS: 1 # build without transform-remove-console babel plugin

jobs:
  e2e:
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Buildcache
        uses: mikehardy/buildcache-action@v2

      - name: Setup Docker Colima 1
        uses: douglascamata/setup-docker-macos-action@v1-alpha
        id: docker1
        continue-on-error: true

      - name: Setup Docker Colima 2
        if: steps.docker1.outcome != 'success'
        uses: douglascamata/setup-docker-macos-action@v1-alpha
        id: docker2
        continue-on-error: true

      - name: Setup Docker Default
        if: steps.docker1.outcome != 'success' && steps.docker2.outcome != 'success'
        uses: docker-practice/actions-setup-docker@1.0.12
        timeout-minutes: 30

      - name: Install AppleSimulatorUtils
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew && brew install applesimutils

      - name: Run regtest setup
        run: cd docker && mkdir lnd && chmod 777 lnd && docker-compose up -d

      - name: Wait for bitcoind
        timeout-minutes: 2
        run: while ! nc -z '127.0.0.1' 43782; do sleep 1; done

      - name: Wait for electrum server
        timeout-minutes: 2
        run: while ! nc -z '127.0.0.1' 60001; do sleep 1; done

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn' # cache packages, but not node_modules

      - name: Activate enviroment variables
        run: cp .env.test.template .env

      - name: Activate react-native-skia-stub
        run: patch -p1 < .github/workflows/react-native-skia-stub.patch

      - name: Detox Framework Cache
        uses: actions/cache@v3
        with:
          path: ~/Library/Detox/ios
          key: detox-framework-cache-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn Install
        run: yarn --no-audit --prefer-offline || yarn --no-audit --prefer-offline
        env:
          HUSKY: 0

      - name: Cache Pods
        uses: actions/cache@v3
        id: podcache
        with:
          path: ios/Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}

      - name: Pod Install
        run: pod install --project-directory=ios || pod install --project-directory=ios

      - name: Build
        run: yarn e2e:build:ios-release

      - name: Test attempt 1
        continue-on-error: true
        id: test1
        run: yarn e2e:test:ios-release --record-videos all --take-screenshots all --record-logs all

      - name: Test attempt 2
        continue-on-error: true
        id: test2
        if: steps.test1.outcome != 'success'
        run: yarn e2e:test:ios-release --record-videos all --take-screenshots all --record-logs all

      - name: Test attempt 3
        continue-on-error: true
        id: test3
        if: steps.test1.outcome != 'success' && steps.test2.outcome != 'success'
        run: yarn e2e:test:ios-release --record-videos all --take-screenshots all --record-logs all

      - name: Test attempt 4
        id: test4
        if: steps.test1.outcome != 'success' && steps.test2.outcome != 'success' && steps.test3.outcome != 'success'
        run: yarn e2e:test:ios-release --record-videos all --take-screenshots all --record-logs all

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2e-test-videos
          path: ./artifacts/

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
